"""
Loan Repayment schedule — Pack 7.41.

One row per (loan x period_year x period_quarter). Generated by linear
amortization service for any loan that has date_get + date_due + debt_usd,
or manually edited via the credit-portfolio scenarios admin section.

`is_custom_schedule = True` marks rows that came from explicit parsing of
loan.notes (custom repayment terms in the contract text). Auto-generated
quarterly schedule has `is_custom_schedule = False`.

Status lifecycle:
  scheduled  -> paid (if actual_paid_amount_usd ~= scheduled_amount_usd)
  scheduled  -> partial (actual < scheduled but >0)
  scheduled  -> overdue (payment_date > expected_period_end)
  scheduled  -> rescheduled (moved to a different period via scenario)
  scheduled  -> forgiven (zeroed out via scenario state_forgiveness_pct)
"""
from typing import Optional
from decimal import Decimal
from datetime import date
from uuid import UUID as PyUUID

from sqlalchemy import (
    Boolean,
    Date,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.base import TimestampMixin, UUIDMixin


REPAYMENT_STATUSES = (
    "scheduled",
    "paid",
    "partial",
    "overdue",
    "rescheduled",
    "forgiven",
)


class LoanRepayment(Base, UUIDMixin, TimestampMixin):
    """One scheduled or actual payment for a single quarter of a single loan."""

    __tablename__ = "loan_repayments"

    loan_id: Mapped[PyUUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("cp_loans.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    period_year: Mapped[int] = mapped_column(Integer, nullable=False, index=True)
    period_quarter: Mapped[int] = mapped_column(Integer, nullable=False)  # 1..4

    # Linear-amortization amounts (or custom from notes)
    scheduled_amount_currency: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(20, 2), nullable=True
    )
    scheduled_amount_usd: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(20, 2), nullable=True
    )

    # Actual payment (set after the fact)
    actual_paid_amount_currency: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(20, 2), nullable=True
    )
    actual_paid_amount_usd: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(20, 2), nullable=True
    )

    status: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="scheduled", index=True
    )
    payment_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)

    # True = parsed from loan.notes (custom contract terms)
    # False = generated by linear quarterly amortization
    is_custom_schedule: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )

    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Relationship
    loan = relationship("CreditPortfolioLoan", lazy="select")

    __table_args__ = (
        UniqueConstraint(
            "loan_id", "period_year", "period_quarter", name="uq_repay_loan_period"
        ),
    )


# Indexes for common aggregations
Index("ix_repay_period", LoanRepayment.period_year, LoanRepayment.period_quarter)
Index("ix_repay_status_period", LoanRepayment.status, LoanRepayment.period_year)
