"""Application configuration loaded from environment variables.
Includes the state-grade information-security baseline."""
from functools import lru_cache
from pathlib import Path
from typing import List, Optional

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application settings loaded from environment / .env file."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=True,
        extra="ignore",
    )

    # --- Environment ---
    ENVIRONMENT: str = "development"
    LOG_LEVEL: str = "INFO"
    LOG_FORMAT: str = "json"  # json | text

    # --- Database ---
    DATABASE_URL: str = Field(
        default="postgresql+asyncpg://uza:uza_dev_pass@localhost:5432/uzassets",
    )
    DATABASE_URL_SYNC: str = Field(
        default="postgresql+psycopg://uza:uza_dev_pass@localhost:5432/uzassets",
    )
    DATABASE_ECHO: bool = False
    DATABASE_POOL_SIZE: int = 10
    DATABASE_MAX_OVERFLOW: int = 20

    # =================================================================
    # AUTH / JWT
    # State-grade baseline: RS256 (asymmetric) preferred over HS256.
    # Keys live in `/app/keys/`, generated by `scripts/generate-keys.sh`.
    # =================================================================
    JWT_ALGORITHM: str = "RS256"  # RS256 | HS256
    JWT_PRIVATE_KEY_PATH: str = "/app/keys/jwt_private.pem"
    JWT_PUBLIC_KEY_PATH:  str = "/app/keys/jwt_public.pem"
    # HS256 fallback secret (only used when JWT_ALGORITHM == HS256)
    JWT_SECRET: str = "change_me_in_production_minimum_32_chars_long_secret"
    JWT_ISSUER:   str = "uzassets-platform"
    JWT_AUDIENCE: str = "uzassets-platform"
    JWT_EXPIRE_MINUTES: int = 30           # access token: short
    JWT_REFRESH_EXPIRE_DAYS: int = 14      # refresh token: rotates

    # =================================================================
    # PASSWORD POLICY (state baseline)
    # =================================================================
    PASSWORD_MIN_LENGTH: int = 12
    PASSWORD_REQUIRE_LOWER:   bool = True
    PASSWORD_REQUIRE_UPPER:   bool = True
    PASSWORD_REQUIRE_DIGIT:   bool = True
    PASSWORD_REQUIRE_SYMBOL:  bool = True
    PASSWORD_HISTORY_SIZE: int = 5         # cannot reuse last N hashes
    PASSWORD_MAX_AGE_DAYS: int = 90        # forced rotation
    BCRYPT_ROUNDS: int = 12

    # --- Account lockout ---
    LOGIN_MAX_FAILED_ATTEMPTS: int = 5
    LOGIN_LOCKOUT_MINUTES: int = 30

    # --- Session ---
    SESSION_IDLE_TIMEOUT_MINUTES: int = 30
    SESSION_ABSOLUTE_TIMEOUT_HOURS: int = 12

    # =================================================================
    # FIELD-LEVEL ENCRYPTION (Fernet)
    # =================================================================
    FERNET_KEY_PATH: str = "/app/keys/fernet.key"

    # =================================================================
    # AUDIT LOG INTEGRITY (HMAC chain)
    # =================================================================
    AUDIT_HMAC_SECRET_PATH: str = "/app/keys/audit_hmac.key"
    AUDIT_RETENTION_DAYS: int = 1825  # 5 years (state baseline)

    # =================================================================
    # RATE LIMITING (per IP / per user)
    # =================================================================
    RATE_LIMIT_AUTH:    str = "10/minute"   # /auth/login, /auth/refresh
    RATE_LIMIT_API:     str = "300/minute"
    RATE_LIMIT_HEAVY:   str = "30/minute"   # /reports/*, /export/*
    RATE_LIMIT_ENABLED: bool = True

    # =================================================================
    # NETWORK / CORS / TRUSTED HOSTS
    # =================================================================
    CORS_ORIGINS: str = (
        "http://localhost:5173,http://localhost,"
        "http://uzassets006,http://uzassets006:5173,http://uzassets006:80,"
        "https://uzassets006,https://uzassets006.uz-assets.uz"
    )
    TRUSTED_HOSTS: str = (
        "localhost,127.0.0.1,backend,uza-backend,nginx,"
        "uzassets006,uzassets006.uz-assets.uz"
    )
    FORCE_HTTPS: bool = False               # set True in production
    HSTS_MAX_AGE_SECONDS: int = 31_536_000  # 1 year
    HSTS_PRELOAD: bool = True
    REQUEST_BODY_MAX_BYTES: int = 25 * 1024 * 1024  # 25 MB

    @property
    def cors_origins_list(self) -> List[str]:
        # CORS origins are URLs — schemes/hosts must match exactly per spec,
        # but we normalize host casing because Windows hostnames are case-insensitive.
        return [
            self._normalize_origin(o.strip())
            for o in self.CORS_ORIGINS.split(",") if o.strip()
        ]

    @staticmethod
    def _normalize_origin(origin: str) -> str:
        """Lowercase the host part of an origin URL while keeping the scheme/port intact."""
        try:
            from urllib.parse import urlparse, urlunparse
            p = urlparse(origin)
            if not p.netloc:
                return origin
            host = p.hostname or ""
            netloc = host.lower()
            if p.port:
                netloc = f"{netloc}:{p.port}"
            return urlunparse((p.scheme, netloc, p.path, p.params, p.query, p.fragment))
        except Exception:
            return origin

    @property
    def trusted_hosts_list(self) -> List[str]:
        # Trusted hosts are bare hostnames; normalize to lowercase.
        # Windows machine names like UZASSETS006 may be sent as-is by clients.
        return [h.strip().lower() for h in self.TRUSTED_HOSTS.split(",") if h.strip()]

    # =================================================================
    # OWNER / BOOTSTRAP
    # =================================================================
    PLATFORM_OWNER_EMAIL: str = "v.kim@uz-assets.uz"
    PLATFORM_URL: str = "https://platform.uz-assets.uz"

    # =================================================================
    # AI
    # =================================================================
    ANTHROPIC_API_KEY: str = ""
    ANTHROPIC_MODEL: str = "claude-opus-4-7"

    # =================================================================
    # FILES / UPLOADS
    # =================================================================
    UPLOAD_DIR: str = "/app/uploads"
    MAX_UPLOAD_SIZE_MB: int = 50

    @property
    def is_production(self) -> bool:
        return self.ENVIRONMENT.lower() == "production"

    # ---------- Helpers to read keys from disk ----------
    def read_jwt_private_key(self) -> Optional[str]:
        p = Path(self.JWT_PRIVATE_KEY_PATH)
        return p.read_text() if p.is_file() else None

    def read_jwt_public_key(self) -> Optional[str]:
        p = Path(self.JWT_PUBLIC_KEY_PATH)
        return p.read_text() if p.is_file() else None

    def read_fernet_key(self) -> Optional[bytes]:
        p = Path(self.FERNET_KEY_PATH)
        return p.read_bytes().strip() if p.is_file() else None

    def read_audit_hmac_secret(self) -> Optional[bytes]:
        p = Path(self.AUDIT_HMAC_SECRET_PATH)
        return p.read_bytes().strip() if p.is_file() else None


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
