"""AUTO-GENERATED moderation route classification (Phase 2).

Капабилити-карта: каждый state-changing маршрут отнесён к бакету —
  A  = мутация данных дашборда, МОДЕРИРУЕМА (module+action; needs_handler —
       у модуля пока нет apply-хендлера, завести в Фазе 4);
  B  = self-service/личное, пишет напрямую;
  C  = система/админ, пишет напрямую;
  D  = upload/multipart (бинарь; JSON-commit половина импорта — уже в A);
  N  = не пишет БД (compute/parse/validate) — исключён.

ЭТО НЕ ПОЛИТИКА, А ТЕХНИЧЕСКАЯ КАРТА (что МОЖНО модерировать и чем применять).
Политика «что модерируется и для кого» — в DB-конфиге/панели (Фаза 3/5).

Файл СГЕНЕРИРОВАН и держится в актуальности CI-тестом
tests/test_moderation_route_coverage.py: новый write-роут не пройдёт тест,
пока не классифицирован здесь (deny-by-default на уровне процесса).
"""
from __future__ import annotations

from typing import NamedTuple, Optional


class RouteClass(NamedTuple):
    bucket: str                 # "A" | "B" | "C" | "D" | "N"
    module: Optional[str] = None    # canonical module (bucket A)
    action: Optional[str] = None    # write action (bucket A)
    needs_handler: bool = False     # A-модуль без apply-хендлера (Фаза 4)


# Ключ = "<route_file_stem>:<endpoint_func>:<METHOD>"
ROUTE_CLASS: dict[str, RouteClass] = {
    "admin_broadcasts:create_template:POST": RouteClass("C"),
    "admin_broadcasts:delete_template:DELETE": RouteClass("C"),
    "admin_broadcasts:update_template:PATCH": RouteClass("C"),
    "admin_broadcasts:send_now:POST": RouteClass("C"),
    "admin_broadcasts:test_on_self:POST": RouteClass("C"),
    "admin_broadcasts:toggle_template:POST": RouteClass("C"),
    "admin_broadcasts:ack:POST": RouteClass("B"),
    "admin_mfa:force_disable_mfa:POST": RouteClass("C"),
    "ai:set_ai_access_mode:PUT": RouteClass("C"),
    "ai:set_ai_activation:PUT": RouteClass("C"),
    "ai:ai_bp_analysis:POST": RouteClass("N"),
    "ai:chat:POST": RouteClass("B"),
    "ai:update_ai_config:PUT": RouteClass("B"),
    "ai:create_conversation:POST": RouteClass("B"),
    "ai:delete_conversation:DELETE": RouteClass("B"),
    "ai:rename_conversation:PATCH": RouteClass("B"),
    "ai:exec_sector_brief:POST": RouteClass("C"),
    "ai:ai_forecast:POST": RouteClass("N"),
    "ai:ai_hlf_analysis:POST": RouteClass("N"),
    "ai:ai_kpi_analysis:POST": RouteClass("N"),
    "ai:save_ai_output:PUT": RouteClass("C"),
    "api_catalog:try_endpoint:POST": RouteClass("N"),
    "api_keys:create_key:POST": RouteClass("C"),
    "api_keys:create_service_account:POST": RouteClass("C"),
    "api_keys:delete_service_account:DELETE": RouteClass("C"),
    "api_keys:update_service_account:PATCH": RouteClass("C"),
    "api_keys:update_key:PATCH": RouteClass("C"),
    "api_keys:revoke_key:POST": RouteClass("C"),
    "attachments:delete_company_attachment:DELETE": RouteClass("A", "documents", "delete", True),
    "attachments:upload_company_attachment:POST": RouteClass("D"),
    "attachments:delete_project_attachment:DELETE": RouteClass("A", "documents", "delete", True),
    "attachments:upload_project_attachment:POST": RouteClass("D"),
    "attachments:delete_task_attachment:DELETE": RouteClass("A", "documents", "delete", True),
    "attachments:upload_task_attachment:POST": RouteClass("D"),
    "attachments:deny_user:POST": RouteClass("C"),
    "attachments:allow_user:DELETE": RouteClass("C"),
    "audit:purge_audit:POST": RouteClass("C"),
    "auth:change_password:POST": RouteClass("B"),
    "auth:login:POST": RouteClass("B"),
    "auth:logout:POST": RouteClass("B"),
    "auth:update_me:PATCH": RouteClass("B"),
    "auth:dismiss_welcome:POST": RouteClass("B"),
    "auth:reauth:POST": RouteClass("B"),
    "auth:refresh:POST": RouteClass("B"),
    "auth:revoke_other_sessions:POST": RouteClass("B"),
    "auth:revoke_one_session:DELETE": RouteClass("B"),
    "auth_mfa:login_mfa:POST": RouteClass("B"),
    "auth_mfa:verify_mfa:POST": RouteClass("B"),
    # Все три bulk-ingest-роута Конструктора/ИИ-импорта модерируются ПОД builder
    # и применяются builder-хендлером (он повторяет builder-persist). Раньше
    # bulk-kpi/bulk-financials числились под kpi/financials, но их apply-shape
    # (сырые ИИ-строки с именами компаний) не совпадает с kpi/financials
    # хендлерами — маршрутизация туда сломала бы применение.
    "builder:bulk_create:POST": RouteClass("A", "builder", "create", False),
    "builder:bulk_create_financials:POST": RouteClass("A", "builder", "create", False),
    "builder:bulk_create_kpi:POST": RouteClass("A", "builder", "create", False),
    "builder:ingest_document:POST": RouteClass("D"),
    "business_plan:bulk_upsert:POST": RouteClass("A", "business_plan", "bulk_upsert", False),
    "business_plan:upsert_comment:PUT": RouteClass("A", "comments", "comment", False),
    "business_plan:upsert_one:POST": RouteClass("A", "business_plan", "edit", False),
    "business_plan:delete_year:DELETE": RouteClass("A", "business_plan", "delete", False),
    "calendar:get_ical_token:POST": RouteClass("B"),
    "comments:mark_comments_read:POST": RouteClass("B"),
    "comments:delete_project_comment:DELETE": RouteClass("A", "comments", "delete", False),
    "comments:update_project_comment:PATCH": RouteClass("A", "comments", "edit", False),
    "comments:delete_task_comment:DELETE": RouteClass("A", "comments", "delete", False),
    "comments:update_task_comment:PATCH": RouteClass("A", "comments", "edit", False),
    "comments:create_project_comment:POST": RouteClass("A", "comments", "comment", False),
    "comments:create_task_comment:POST": RouteClass("A", "comments", "comment", False),
    "companies:create_company:POST": RouteClass("A", "companies", "create", False),
    "companies:create_sector:POST": RouteClass("C"),
    "companies:delete_sector:DELETE": RouteClass("C"),
    "companies:update_sector:PATCH": RouteClass("C"),
    "companies:delete_company:DELETE": RouteClass("A", "companies", "delete", False),
    "companies:update_company:PATCH": RouteClass("A", "companies", "edit", False),
    "companies:delete_company_financials:DELETE": RouteClass("A", "financials", "delete", False),
    "companies_admin_v2:create_company_admin:POST": RouteClass("C"),
    "companies_admin_v2:delete_company_admin:DELETE": RouteClass("C"),
    "companies_admin_v2:update_company_admin:PATCH": RouteClass("C"),
    "companies_admin_v2:replace_year_overrides:PUT": RouteClass("C"),
    "companies_admin_v2:create_sector_admin:POST": RouteClass("C"),
    "companies_admin_v2:delete_sector_admin:DELETE": RouteClass("C"),
    "companies_admin_v2:update_sector_admin:PATCH": RouteClass("C"),
    "company_library:post_company_ws_ticket:POST": RouteClass("B"),
    "company_library:create_field_definition:POST": RouteClass("C"),
    "company_library:delete_field_definition:DELETE": RouteClass("C"),
    "company_library:update_field_definition:PATCH": RouteClass("C"),
    "company_library:create_tab:POST": RouteClass("C"),
    "company_library:delete_tab:DELETE": RouteClass("C"),
    "company_library:update_tab:PATCH": RouteClass("C"),
    "company_library:create_view:POST": RouteClass("B"),
    "company_library:delete_view:DELETE": RouteClass("B"),
    "company_library:update_view:PATCH": RouteClass("B"),
    "company_library:write_library_field:PATCH": RouteClass("A", "company_library", "edit", True),
    "consultants:create_consultant:POST": RouteClass("A", "consultants", "create", True),
    "consultants:delete_consultant:DELETE": RouteClass("A", "consultants", "delete", True),
    "consultants:update_consultant:PATCH": RouteClass("A", "consultants", "edit", True),
    "credit_portfolio:upsert_fx_rate:PUT": RouteClass("A", "credit", "edit", False),
    "credit_portfolio:create_loan:POST": RouteClass("A", "credit", "create", False),
    "credit_portfolio:bulk_import:POST": RouteClass("A", "credit", "create", False),
    "credit_portfolio:delete_loan:DELETE": RouteClass("A", "credit", "delete", False),
    "credit_portfolio:update_loan:PUT": RouteClass("A", "credit", "edit", False),
    "credit_portfolio:create_loan_payment:POST": RouteClass("A", "credit", "create", False),
    "credit_portfolio:delete_payment:DELETE": RouteClass("A", "credit", "delete", False),
    "credit_portfolio:update_payment:PATCH": RouteClass("A", "credit", "edit", False),
    "credit_scenario:apply_migrations_endpoint:POST": RouteClass("C"),
    "credit_scenario:create_custom_indicator:POST": RouteClass("C"),
    "credit_scenario:delete_custom_indicator:DELETE": RouteClass("C"),
    "credit_scenario:update_custom_indicator:PUT": RouteClass("C"),
    "credit_scenario:formula_test:POST": RouteClass("N"),
    "credit_scenario:formula_validate:POST": RouteClass("N"),
    "credit_scenario:delete_loan_override:DELETE": RouteClass("C"),
    "credit_scenario:upsert_loan_override:PUT": RouteClass("C"),
    "credit_scenario:create_scenario:POST": RouteClass("C"),
    "credit_scenario:delete_scenario:DELETE": RouteClass("C"),
    "credit_scenario:update_scenario:PUT": RouteClass("C"),
    "custom_api:create_endpoint:POST": RouteClass("C"),
    "custom_api:delete_endpoint:DELETE": RouteClass("C"),
    "custom_api:update_endpoint:PATCH": RouteClass("C"),
    "custom_api:preview:POST": RouteClass("N"),
    "db_admin:execute_query:POST": RouteClass("C"),
    "db_admin:delete_row:DELETE": RouteClass("C"),
    "db_admin:update_row:PATCH": RouteClass("C"),
    "directions:create_direction:POST": RouteClass("A", "directions", "create", True),
    "directions:delete_direction:DELETE": RouteClass("A", "directions", "delete", True),
    "directions:update_direction:PATCH": RouteClass("A", "directions", "edit", True),
    "documents:create_folder:POST": RouteClass("A", "documents", "create", True),
    "documents:delete_folder:DELETE": RouteClass("A", "documents", "delete", True),
    "documents:patch_folder:PATCH": RouteClass("A", "documents", "edit", True),
    "documents:delete_item:DELETE": RouteClass("A", "documents", "delete", True),
    "documents:patch_item:PATCH": RouteClass("A", "documents", "edit", True),
    "documents:add_link:POST": RouteClass("A", "documents", "create", True),
    "documents:drop_link:DELETE": RouteClass("A", "documents", "delete", True),
    "documents:restore_item:POST": RouteClass("A", "documents", "edit", True),
    "documents:upload_document:POST": RouteClass("D"),
    "elasticity:apply_migrations_endpoint:POST": RouteClass("C"),
    "elasticity:upsert_coefficient:PUT": RouteClass("A", "elasticity", "edit", True),
    "elasticity:delete_coefficient:DELETE": RouteClass("A", "elasticity", "delete", True),
    "elasticity:upsert_project_effect:PUT": RouteClass("A", "elasticity", "edit", True),
    "elasticity:delete_project_effect:DELETE": RouteClass("A", "elasticity", "delete", True),
    "email_settings:update_email_settings:PUT": RouteClass("C"),
    "email_settings:send_test_email:POST": RouteClass("C"),
    "esg:create_issue:POST": RouteClass("A", "esg", "create_issue", False),
    "esg:delete_issue:DELETE": RouteClass("A", "esg", "delete", False),
    "esg:update_issue:PATCH": RouteClass("A", "esg", "update_issue", False),
    "esg:add_esg_kpi:POST": RouteClass("A", "esg", "create", False),
    "esg:upsert_maturity_cell:PUT": RouteClass("A", "esg", "upsert_maturity_cell", False),
    "esg:upsert_metric:PUT": RouteClass("A", "esg", "upsert_metric", False),
    "esg:delete_metric:DELETE": RouteClass("A", "esg", "delete", False),
    "esg:upsert_report:PUT": RouteClass("A", "esg", "upsert_report", False),
    "esg:upsert_swot:PUT": RouteClass("A", "esg", "upsert_swot", False),
    "esg:delete_swot:DELETE": RouteClass("A", "esg", "delete_swot", False),
    "external_apis:create_external_api:POST": RouteClass("C"),
    "external_apis:delete_external_api:DELETE": RouteClass("C"),
    "external_apis:update_external_api:PATCH": RouteClass("C"),
    "external_apis:remove_openapi:DELETE": RouteClass("C"),
    "external_apis:upload_openapi:POST": RouteClass("C"),
    "financials:create_report:POST": RouteClass("A", "financials", "create", False),
    "financials:save_company_hlf:PUT": RouteClass("A", "financials", "edit", False),
    "financials:save_ifrs_editor:PUT": RouteClass("A", "financials", "edit", False),
    "financials:parse_ifrs_editor_excel:POST": RouteClass("D"),
    "financials:save_company_indicators:PUT": RouteClass("A", "financials", "edit", False),
    "financials:save_nsbu_editor:PUT": RouteClass("A", "financials", "edit", False),
    "financials:parse_nsbu_editor_excel:POST": RouteClass("D"),
    "financials:detailed_import_confirm:POST": RouteClass("A", "financials", "create", False),
    "financials:import_detailed_excel:POST": RouteClass("D"),
    "financials:detailed_parse_preview:POST": RouteClass("D"),
    "financials:update_detailed_cell:PUT": RouteClass("A", "financials", "edit", False),
    "financials:delete_detailed_line:DELETE": RouteClass("A", "financials", "delete", False),
    "financials:update_detailed_line_mapping:PUT": RouteClass("A", "financials", "edit", False),
    "financials:import_hlf_file:POST": RouteClass("D"),
    "financials:save_soe_health_params:PUT": RouteClass("C"),
    "financials:delete_report:DELETE": RouteClass("A", "financials", "delete", False),
    "financials:save_report:PUT": RouteClass("A", "financials", "edit", False),
    "finmodel:regenerate_forecast:POST": RouteClass("A", "finmodel", "edit", True),
    "finmodel:import_excel_commit:POST": RouteClass("A", "finmodel", "create", True),
    "finmodel:import_excel_preview:POST": RouteClass("D"),
    "finmodel:create_scenario:POST": RouteClass("A", "finmodel", "create", True),
    "finmodel:delete_scenario:DELETE": RouteClass("A", "finmodel", "delete", True),
    "finmodel:activate_scenario:POST": RouteClass("A", "finmodel", "status_change", True),
    "finmodel:delete_year:DELETE": RouteClass("A", "finmodel", "delete", True),
    "finmodel:create_year:POST": RouteClass("A", "finmodel", "create", True),
    "finmodel:copy_year:POST": RouteClass("A", "finmodel", "create", True),
    "finmodel:lock_year:POST": RouteClass("A", "finmodel", "status_change", True),
    "finmodel:unlock_year:POST": RouteClass("A", "finmodel", "status_change", True),
    "finmodel:patch_cell:PATCH": RouteClass("A", "finmodel", "edit", True),
    "finmodel:patch_cells_batch:PATCH": RouteClass("A", "finmodel", "edit", True),
    "finmodel:add_comment:POST": RouteClass("B"),
    "finmodel:delete_comment:DELETE": RouteClass("B"),
    "finmodel:put_macro:PUT": RouteClass("A", "finmodel", "edit", True),
    "forensic:update_forensic_company:PUT": RouteClass("A", "procurement", "update_company", False),
    "forensic:clear_forensic_year:DELETE": RouteClass("A", "procurement", "delete", False),
    "forensic:import_forensic_excel:POST": RouteClass("D"),
    "forgot_password:forgot_init:POST": RouteClass("B"),
    "forgot_password:forgot_verify:POST": RouteClass("B"),
    "governance:upsert_committee_meeting:PUT": RouteClass("A", "governance", "edit", False),
    "governance:create_committee_period:POST": RouteClass("A", "governance", "create", False),
    "governance:upsert_governance_data:PUT": RouteClass("A", "governance", "upsert_data", False),
    "governance:create_board_member:POST": RouteClass("A", "governance", "create_member", False),
    "governance:delete_board_member:DELETE": RouteClass("A", "governance", "delete", False),
    "governance:update_board_member:PATCH": RouteClass("A", "governance", "update_member", False),
    "ifrs_report_history:upsert_history:PUT": RouteClass("A", "ifrs_report_history", "edit", True),
    "invest_projects:delete_path:DELETE": RouteClass("A", "investment", "delete", False),
    "invest_projects:patch_path:PATCH": RouteClass("A", "investment", "edit", False),
    "invest_projects:put_path:PUT": RouteClass("A", "investment", "replace", False),
    "knowledge:reindex:POST": RouteClass("C"),
    "knowledge:upload:POST": RouteClass("D"),
    "knowledge:delete_doc:DELETE": RouteClass("C"),
    "kpi:upsert_comment:PUT": RouteClass("A", "kpi", "edit", False),
    "kpi:load_ngmk_template_compat:POST": RouteClass("A", "kpi", "import", False),
    "kpi:load_template:POST": RouteClass("A", "kpi", "import", False),
    "kpi:delete_year:DELETE": RouteClass("A", "kpi", "delete", False),
    "kpi:replace_company_year:PUT": RouteClass("A", "kpi", "replace_year", False),
    "mfa:disable_mfa:POST": RouteClass("B"),
    "mfa:enable_mfa:POST": RouteClass("B"),
    "mfa:regenerate_recovery_codes:POST": RouteClass("B"),
    "moderation:remove_moderator:DELETE": RouteClass("C"),
    "moderation:restore_moderator:POST": RouteClass("C"),
    "moderation:set_moderation_policy:PATCH": RouteClass("C"),
    "moderation:create_submission:POST": RouteClass("C"),
    "moderation:approve_submission:POST": RouteClass("C"),
    "moderation:add_comment:POST": RouteClass("C"),
    "moderation:reject_submission:POST": RouteClass("C"),
    "moderation:retry_apply_submission:POST": RouteClass("C"),
    "moderation:set_review_submission:POST": RouteClass("C"),
    "moderation:withdraw_submission:POST": RouteClass("C"),
    "moderation:patch_user_flags:PATCH": RouteClass("C"),
    "monitoring:exec_brief:POST": RouteClass("N"),
    "monitoring:create_snapshot:POST": RouteClass("C"),
    "monitoring:delete_snapshot:DELETE": RouteClass("C"),
    "notes:create_note:POST": RouteClass("A", "notes", "create", True),
    "notes:patch_checklist_item:PATCH": RouteClass("A", "notes", "edit", True),
    "notes:delete_note:DELETE": RouteClass("A", "notes", "delete", True),
    "notes:update_note:PATCH": RouteClass("A", "notes", "edit", True),
    "notifications:post_archive_bulk:POST": RouteClass("B"),
    "notifications:post_broadcast:POST": RouteClass("C"),
    "notifications:update_prefs:PUT": RouteClass("B"),
    "notifications:post_read_all:POST": RouteClass("B"),
    "notifications:post_read_bulk:POST": RouteClass("B"),
    "notifications:post_read_by:POST": RouteClass("B"),
    "notifications:send_one:POST": RouteClass("C"),
    "notifications:post_test:POST": RouteClass("C"),
    "notifications:post_ws_ticket:POST": RouteClass("B"),
    "notifications:post_archive_one:POST": RouteClass("B"),
    "notifications:post_read_one:POST": RouteClass("B"),
    "overview_matrix:save_matrix_config:PUT": RouteClass("A", "overview_matrix", "replace", True),
    "partners:create_partner:POST": RouteClass("C"),
    "partners:delete_partner:DELETE": RouteClass("C"),
    "partners:update_partner:PATCH": RouteClass("C"),
    "partners:detach_resource:DELETE": RouteClass("C"),
    "partners:attach_resource:POST": RouteClass("C"),
    "pmo:delete_change:DELETE": RouteClass("A", "pmo", "delete", True),
    "pmo:update_change:PATCH": RouteClass("A", "pmo", "edit", True),
    "pmo:delete_charter:DELETE": RouteClass("A", "pmo", "delete", True),
    "pmo:update_charter:PATCH": RouteClass("A", "pmo", "edit", True),
    "pmo:create_change:POST": RouteClass("A", "pmo", "create", True),
    "pmo:create_charter:POST": RouteClass("A", "pmo", "create", True),
    "pmo:create_lesson:POST": RouteClass("A", "pmo", "create", True),
    "pmo:create_raci:POST": RouteClass("A", "pmo", "create", True),
    "pmo:create_raid:POST": RouteClass("A", "pmo", "create", True),
    "pmo:create_sprint:POST": RouteClass("A", "pmo", "create", True),
    "pmo:create_stakeholder:POST": RouteClass("A", "pmo", "create", True),
    "pmo:create_status_report:POST": RouteClass("A", "pmo", "create", True),
    "pmo:create_dependency:POST": RouteClass("A", "pmo", "create", True),
    "pmo:delete_dependency:DELETE": RouteClass("A", "pmo", "delete", True),
    "pmo:delete_lesson:DELETE": RouteClass("A", "pmo", "delete", True),
    "pmo:update_lesson:PATCH": RouteClass("A", "pmo", "edit", True),
    "pmo:delete_raci:DELETE": RouteClass("A", "pmo", "delete", True),
    "pmo:update_raci:PATCH": RouteClass("A", "pmo", "edit", True),
    "pmo:delete_raid:DELETE": RouteClass("A", "pmo", "delete", True),
    "pmo:update_raid:PATCH": RouteClass("A", "pmo", "edit", True),
    "pmo:delete_sprint:DELETE": RouteClass("A", "pmo", "delete", True),
    "pmo:update_sprint:PATCH": RouteClass("A", "pmo", "edit", True),
    "pmo:delete_stakeholder:DELETE": RouteClass("A", "pmo", "delete", True),
    "pmo:update_stakeholder:PATCH": RouteClass("A", "pmo", "edit", True),
    "pmo:patch_task_agile:PATCH": RouteClass("A", "tasks", "status_change", False),
    "presence:heartbeat:POST": RouteClass("B"),
    "procurement_analysis:clear_closures:DELETE": RouteClass("A", "procurement", "delete", False),
    "procurement_analysis:import_closures_excel:POST": RouteClass("D"),
    "procurement_analysis:update_closure:PUT": RouteClass("A", "procurement", "edit", False),
    "production:update_production_company:PUT": RouteClass("A", "production", "upsert_company", False),
    "production:import_production_xlsx:POST": RouteClass("D"),
    "projects:create_project:POST": RouteClass("A", "projects", "create", False),
    "projects:archive_project:DELETE": RouteClass("A", "projects", "delete", False),
    "projects:update_project:PATCH": RouteClass("A", "projects", "edit", False),
    "projects:toggle_project_result:POST": RouteClass("A", "projects", "edit", False),
    "ratings:create_rating:POST": RouteClass("A", "ratings", "create", False),
    "ratings:delete_rating:DELETE": RouteClass("A", "ratings", "delete", False),
    "ratings:update_rating:PATCH": RouteClass("A", "ratings", "update", False),
    "rbac_v3:create_group:POST": RouteClass("C"),
    "rbac_v3:delete_group:DELETE": RouteClass("C"),
    "rbac_v3:update_group:PATCH": RouteClass("C"),
    "rbac_v3:set_group_members:PUT": RouteClass("C"),
    "rbac_v3:set_group_permissions:PUT": RouteClass("C"),
    "rbac_v3:create_role:POST": RouteClass("C"),
    "rbac_v3:delete_role:DELETE": RouteClass("C"),
    "rbac_v3:update_role:PATCH": RouteClass("C"),
    "rbac_v3:update_role_permissions:PATCH": RouteClass("C"),
    "rbac_v3:create_user:POST": RouteClass("C"),
    "rbac_v3:deactivate_user:DELETE": RouteClass("C"),
    "rbac_v3:update_user:PATCH": RouteClass("C"),
    "rbac_v3:force_password_change:POST": RouteClass("C"),
    "rbac_v3:remove_user_membership:DELETE": RouteClass("C"),
    "rbac_v3:upsert_user_membership:PUT": RouteClass("C"),
    "rbac_v3:set_user_owner:POST": RouteClass("C"),
    "rbac_v3:permanently_delete_user:DELETE": RouteClass("C"),
    "rbac_v3:set_user_permissions:PUT": RouteClass("C"),
    "rbac_v3:create_preview_token:POST": RouteClass("C"),
    "rbac_v3:exchange_preview_ticket:POST": RouteClass("C"),
    "rbac_v3:reactivate_user:POST": RouteClass("C"),
    "rbac_v3:reset_password:POST": RouteClass("C"),
    "report_wizard:save_report_wizard:PUT": RouteClass("A", "report_wizard", "edit", True),
    "scenarios:create_scenario:POST": RouteClass("A", "scenarios", "create", True),
    "scenarios:delete_scenario:DELETE": RouteClass("A", "scenarios", "delete", True),
    "scenarios:update_scenario:PATCH": RouteClass("A", "scenarios", "edit", True),
    "scenarios:delete_override:DELETE": RouteClass("A", "scenarios", "delete", True),
    "scenarios:upsert_override:PUT": RouteClass("A", "scenarios", "edit", True),
    "status_updates:create_status_update:POST": RouteClass("A", "status_updates", "create", True),
    "status_updates:delete_status_update:DELETE": RouteClass("A", "status_updates", "delete", True),
    "status_updates:update_status_update:PATCH": RouteClass("A", "status_updates", "edit", True),
    "storage_admin:storage_smoke_test:POST": RouteClass("C"),
    "subsidies:create_subsidy:POST": RouteClass("A", "subsidies", "create", True),
    "subsidies:delete_subsidy:DELETE": RouteClass("A", "subsidies", "delete", True),
    "subsidies:update_subsidy:PUT": RouteClass("A", "subsidies", "edit", True),
    "system_config:create_yearly_rate:POST": RouteClass("C"),
    "system_config:delete_yearly_rate:DELETE": RouteClass("C"),
    "system_config:update_yearly_rate:PATCH": RouteClass("C"),
    "tasks:create_task:POST": RouteClass("A", "tasks", "create", False),
    "tasks:archive_task:DELETE": RouteClass("A", "tasks", "delete", False),
    "tasks:update_task:PATCH": RouteClass("A", "tasks", "status_change", False),
    "tasks:toggle_task_result:POST": RouteClass("A", "tasks", "edit", False),
    "tls_admin:run_letsencrypt:POST": RouteClass("C"),
    "tls_admin:update_schedule:PATCH": RouteClass("C"),
    "tls_admin:upload_cert:POST": RouteClass("C"),
    "unit_cost:unit_cost_save_company:PUT": RouteClass("A", "unit_cost", "edit", False),
    "unit_cost:unit_cost_save_prices:PUT": RouteClass("A", "unit_cost", "edit", False),
    "watches:unfollow:DELETE": RouteClass("B"),
    "watches:follow:POST": RouteClass("B"),
    "webhooks:replay_delivery:POST": RouteClass("C"),
    "webhooks:create_subscription:POST": RouteClass("C"),
    "webhooks:delete_subscription:DELETE": RouteClass("C"),
    "webhooks:update_subscription:PATCH": RouteClass("C"),
    "webhooks:test_subscription:POST": RouteClass("C"),
}


def route_class_for(endpoint_module: str, endpoint_name: str, method: str) -> Optional[RouteClass]:
    """Классификация маршрута по (module-пути эндпоинта, имени, методу). None —
    если не классифицирован (CI-тест такого не допустит)."""
    stem = endpoint_module.rsplit(".", 1)[-1]
    return ROUTE_CLASS.get(f"{stem}:{endpoint_name}:{method.upper()}")


MODERATABLE_MODULES: frozenset[str] = frozenset(
    rc.module for rc in ROUTE_CLASS.values() if rc.bucket == "A" and rc.module
)

# A-модули, у которых ПОКА нет apply-хендлера (одобрение уйдёт в skip) — Фаза 4.
MODULES_NEEDING_HANDLER: frozenset[str] = frozenset(
    rc.module for rc in ROUTE_CLASS.values()
    if rc.bucket == "A" and rc.needs_handler and rc.module
)
